# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeCI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeCI
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  target 'ReactNativeCITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeCI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeCI-tvOS

  target 'ReactNativeCI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
